# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vision_transformers',
                'doc_host': 'https://Jorgvt.github.io',
                'git_url': 'https://github.com/Jorgvt/vision_transformers',
                'lib_path': 'vision_transformers'},
  'syms': {'vision_transformers.core': {'vision_transformers.core.foo': ('core.html#foo', 'vision_transformers/core.py')}}}